#!/usr/bin/env zsh

filename="${1%.*}"

# clang++ -std=c++17 -o "$filename" "$filename.cpp"

clang++ -o "$filename" "$filename.cpp" \
	-std=c++20 \
	-Wall -Wextra -Wformat=2 -Wshadow -Wfloat-equal -Wconversion \
	-Wcast-qual -Wcast-align \
	-pedantic \
	-D LOCAL || exit $?
	# -fsanitize=address,bounds,undefined \


echo $filename
