CompileFlags:                     # Tweak the parse settings
  Add: [
    "-std=c++17", 
    # "-Wall", "-Wextra", "-Wformat=2", "-Wshadow", "-Wfloat-equal", "-Wconversion", "-Wcast-qual", "-Wcast-align", 
    "-fsanitize=address,bounds,undefined",  
    "-D", "LOCAL",
  ]
  Compiler: clang++

